const { db } = require('../config/firebase');
const { COLLECTION_NAME: EXCEL_MASTER_COLLECTION } = require('../models/excelMaster');
const ledgerRemainderService = require('./ledgerRemainder');
const ledgerLogsService = require('./ledgerLogs');
const counterService = require('./counter');

/**
 * Parse date in DD/MM/YYYY format to ISO string
 * Accepts format: dd/mm/yyyy (4-digit year required)
 * Rejects: dd/mm/yy (2-digit year)
 */
function parseDateFormat(dateStr) {
  if (!dateStr) return '';

  // If xlsx parses the cell as an actual Date, accept it.
  if (dateStr instanceof Date) {
    if (isNaN(dateStr.getTime())) return '';
    return dateStr.toISOString().slice(0, 10);
  }

  // If it's an Excel serial date (number), try convert.
  if (typeof dateStr === 'number' && Number.isFinite(dateStr)) {
    // Excel serial dates are typically in the ~40000-60000 range for modern years.
    // If it looks reasonable, convert using the common JS epoch mapping.
    if (dateStr > 1000 && dateStr < 100000) {
      const utc = new Date(Date.UTC(1899, 11, 30) + dateStr * 86400000);
      if (!isNaN(utc.getTime())) return utc.toISOString().slice(0, 10);
    }
    return '';
  }

  if (typeof dateStr !== 'string') return '';

  const s = dateStr.trim();
  if (!s) return '';

  // Accept ISO YYYY-MM-DD directly.
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;

  // Match only dd/mm/yyyy or dd-mm-yyyy format (4-digit year REQUIRED)
  const dateRegex = /^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/;
  const match = s.match(dateRegex);

  if (match) {
    const day = parseInt(match[1], 10);
    const month = parseInt(match[2], 10);
    const year = parseInt(match[3], 10);

    // Validate date
    if (month < 1 || month > 12 || day < 1 || day > 31) {
      return '';
    }

    // Return ISO format (YYYY-MM-DD)
    return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
  }

  // Fallback: try JS Date parsing for strings like "2026-03-29T00:00:00Z"
  const parsed = new Date(s);
  if (!isNaN(parsed.getTime())) return parsed.toISOString().slice(0, 10);

  return '';
}

class OutstandingService {
  /**
   * Process outstanding records from Excel
   * 1. Validates against Ledger_Remainder collection
   * 2. Updates ledger with new debit/credit/date/comments values
   * 3. Creates log entries for audit trail
   * 4. Returns validation results
   */
  async processOutstandingRecords(validRecords, userId = null, fileName = null) {
    const results = {
      processed: 0,
      found: [],
      notFound: [],
      updated: 0,
      logsCreated: 0,
    };

    if (!validRecords.length) {
      return results;
    }

    // Batch pre-fetch full master docs for validation and Outstanding_Remainder creation
    const allLedgerIds = [...new Set(
      validRecords
        .map(r => String(r.ledger || '').trim().replace(/\s+/g, '').toUpperCase())
        .filter(Boolean)
    )];
    const masterDocs = new Map(); // ledger_id -> full master doc data
    for (let i = 0; i < allLedgerIds.length; i += 30) {
      const idBatch = allLedgerIds.slice(i, i + 30);
      const snapshot = await db
        .collection(EXCEL_MASTER_COLLECTION)
        .where('ledger_id', 'in', idBatch)
        .get();
      snapshot.forEach(doc => masterDocs.set(doc.data().ledger_id, doc.data()));
    }

    const logsToCreate = [];

    // Process each record
    for (const record of validRecords) {
      try {
        // ledger_id is generated by removing spaces from ledger name and converting to uppercase
        const ledgerId = String(record.ledger || '')
          .trim()
          .replace(/\s+/g, '')
          .toUpperCase();

        if (!ledgerId) {
          results.notFound.push({
            ledger: record.ledger,
            reason: 'Invalid ledger name',
          });
          continue;
        }

        // Validate: ledger must exist in Excel_master
        if (!masterDocs.has(ledgerId)) {
          results.notFound.push({
            ledger: record.ledger,
            ledger_id: ledgerId,
            reason: 'Ledger not found in Excel master data',
          });
          continue;
        }

        // Parse incoming values (needed for both CREATE and UPDATE paths)
        const parsedDate = parseDateFormat(record.date);
        const newDebit = parseFloat(record.debit || 0) || 0;
        const newCredit = parseFloat(record.credit || 0) || 0;
        const newComments = String(record.comments || '').trim();

        // Find the ledger in Outstanding_Remainder for updating
        const ledgerSnapshot = await db
          .collection('Outstanding_Remainder')
          .where('ledger_id', '==', ledgerId)
          .limit(1)
          .get();

        if (ledgerSnapshot.empty) {
          // Ledger is in master but not yet in Outstanding_Remainder — CREATE it
          const masterData = masterDocs.get(ledgerId);
          const now = new Date().toISOString();
          const newRef = db.collection('Outstanding_Remainder').doc();
          const newRecord = {
            ledger_id: ledgerId,
            ledger_name: masterData.ledger || '',
            city: String(masterData.city || '').trim().toLowerCase(),
            group: String(record.group || masterData.group || '').trim(),
            contact: masterData.contact || '',
            mobile: masterData.mobile || '',
            email: masterData.email || '',
            debit: newDebit,
            credit: newCredit,
            nextCallDate: '',
            lastComments: newComments || '',
            lastTransactionDate: parsedDate || '',
            createdAt: now,
            createdByUserId: userId || null,
            sourceFileName: fileName || null,
            updatedAt: now,
            lastUpdatedAt: now,
            updatedByUserId: userId || null,
          };
          await newRef.set(newRecord);
          results.updated += 1;

          logsToCreate.push({
            ledger_id: ledgerId,
            ledger_name: newRecord.ledger_name,
            group: newRecord.group,
            ldebit: newDebit,
            lcredit: newCredit,
            nextCallDate: '',
            date: parsedDate || String(record.date || '').trim(),
            comments: newComments,
            operation: 'insert',
            updatedFields: ['ldebit', 'lcredit', 'comments'],
            userId,
            city: newRecord.city,
          });

          results.found.push({ ledger: record.ledger, ledger_id: ledgerId, created: true,
            debit: newDebit, credit: newCredit });
          results.processed += 1;
          continue;
        }

        // Get existing ledger document (UPDATE path)
        const ledgerDoc = ledgerSnapshot.docs[0];
        const ledgerRef = ledgerDoc.ref;
        const ledgerData = ledgerDoc.data();

        // Store previous values for audit trail
        const previousDebit = ledgerData.debit || 0;
        const previousCredit = ledgerData.credit || 0;
        const previousDate = ledgerData.lastTransactionDate || '';
        const previousComments = ledgerData.lastComments || '';

        // Avoid duplication: Skip updates if debit, credit, date, and comments are all exactly the same
        if (
          previousDebit === newDebit &&
          previousCredit === newCredit &&
          previousDate === (parsedDate || '') &&
          previousComments === newComments
        ) {
           // Skip updating this record completely
           // Add to found since we matched it, but don't count as updated/logged
           results.found.push({
             ledger: record.ledger,
             ledger_id: ledgerId,
             skipped: true, // Optional marker
             reason: 'Data unchanged from previous upload'
           });
           continue; 
        }

        // Update ledger with new values (REPLACE, not increment)
        const updateData = {
          debit: newDebit,
          credit: newCredit,
          group: String(record.group || '').trim() || ledgerData.group,
          lastUpdatedAt: new Date().toISOString(),
          updatedByUserId: userId || null,
          sourceFileName: fileName || null,
        };

        // Always store date if it exists (dd/mm/yyyy format)
        if (parsedDate) {
          updateData.lastTransactionDate = parsedDate;
        }
        
        // Always store comments (even if empty)
        updateData.lastComments = newComments;

        await ledgerRef.update(updateData);

        results.updated += 1;

        // Determine which fields actually changed for highlighting
        const changedFields = [];
        if (newDebit !== previousDebit) changedFields.push('ldebit');
        if (newCredit !== previousCredit) changedFields.push('lcredit');
        if (newComments !== previousComments) changedFields.push('comments');

        // Create audit log entry
        logsToCreate.push({
          ledger_id: ledgerId,
          ledger_name: ledgerData.ledger_name,
          group: String(record.group || '').trim() || ledgerData.group,
          ldebit: newDebit,
          lcredit: newCredit,
          nextCallDate: '',
          date: parsedDate || String(record.date || '').trim(),
          comments: newComments,
          operation: (previousDebit === 0 && previousCredit === 0) ? 'insert' : 'update',
          updatedFields: changedFields,
          userId,
          city: ledgerData.city || '',
        });

        results.found.push({
          ledger: record.ledger,
          ledger_id: ledgerId,
          debit: newDebit,
          credit: newCredit,
          date: parsedDate || record.date,
          comments: record.comments,
        });

        results.processed += 1;
      } catch (error) {
        console.error('Error processing outstanding record:', error);
        results.notFound.push({
          ledger: record.ledger,
          reason: `Error: ${error.message}`,
        });
      }
    }

    // Create all logs in batch
    if (logsToCreate.length) {
      try {
        const logResult = await ledgerLogsService.addLogs(logsToCreate);
        results.logsCreated = logResult.inserted;
      } catch (error) {
        console.error('Error creating logs:', error);
      }
    }

    // Update all counter fields: src_outstanding, src_outstanding_date, totalLedgers, totaldebit, totalcredit
    try {
      await counterService.updateOutstandingUpload(fileName);
    } catch (e) {
      console.error('[counter] outstanding upload update failed:', e);
    }

    return results;
  }

  /**
   * Get outstanding summary for a ledger
   */
  async getSummary(ledger_id) {
    try {
      const ledgerDoc = await db
        .collection('Outstanding_Remainder')
        .where('ledger_id', '==', ledger_id)
        .limit(1)
        .get();

      if (ledgerDoc.empty) {
        return null;
      }

      const data = ledgerDoc.docs[0].data();
      const logs = await ledgerLogsService.getLogsByLedgerId(ledger_id, { limit: 50 });

      return {
        ledger_id,
        ledger_name: data.ledger_name,
        city: data.city,
        debit: data.debit || 0,
        credit: data.credit || 0,
        logs,
      };
    } catch (error) {
      console.error('Error fetching summary:', error);
      return null;
    }
  }
}

module.exports = new OutstandingService();
